### PR TITLE
View license obligation frontend

### PR DESCRIPTION
**Pull request by AnnieJovitha**
Add front end
1. To view the list of license obligation per project 
2. Also list packages per obligation

### CODE REVIEW

**Comment by AnnieJovitha** [comment]
- 
Screenshot 2021-08-13 at 17 01 47

**Comment by AnnieJovitha** [comment]
Screenshot 2021-08-13 at 17 02 07

**Comment by AnnieJovitha** [comment]
Screenshot 2021-08-13 at 17 02 34

**Comment by JeroenKnoops** [comment]
When you have to include the license text, is it possible to generate that file for a project?
So developers can add that file to the release.

Similar to the implementation of brewfather:
https://docs.brewfather.app/legal/3rd-party-licenses
https://web.brewfather.app/3rdpartylicenses.txt

This can also be done in a separate issue..

**Review by JeroenKnoops — APPROVED** [review]

**Review by Brend-Smits — CHANGES_REQUESTED** [review]
It looks great! 
How do you determine the obligation of a dependency? 

I think we should add a view where you want to see the obligations per license or per project. So if you click on a project, you want to see the obligations that are needed for that specific project. Is this possible?

**Comment by AnnieJovitha** [comment]
> When you have to include the license text, is it possible to generate that file for a project?
> So developers can add that file to the release.
> 
> Similar to the implementation of brewfather:
> https://docs.brewfather.app/legal/3rd-party-licenses
> https://web.brewfather.app/3rdpartylicenses.txt
> 
> This can also be done in a separate issue..

Can be done, but we dont have the license informaiton in the SPDX file as of now. and I have questions on how to deal for the AND and OR scenarios

**Comment by AnnieJovitha** [comment]
> It looks great!
> How do you determine the obligation of a dependency?
> 
> I think we should add a view where you want to see the obligations per license or per project. So if you click on a project, you want to see the obligations that are needed for that specific project. Is this possible?

Viewing the obligations per project is what you see in this PR.
Only 2 obligations are concentrated per project as of now.
1. Must include original copy of license
2. Must distribute source code 

and we get these information from the dependencies, 

And for more information on how we get this information on the license take a look at the back end impelementation.
and read through  https://gitlab.ta.philips.com/swat/bom/comparison/-/blob/master/licenses.md

**Review by Brend-Smits — APPROVED** [review]

**Pull request merged**
